apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: maven
  name: maven-web-application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mavenweb
    spec:
      containers:
      - image: dockerhandson
        name: mavenweb
        ports:
        - name: mavenweb
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mavenweb
  name: mavenweb
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: mavenweb
